#!/usr/bin/env python3
"""
Port the legacy café menu site (legacy-sites/menu-src/armada-menu-site/, from brand/cafe/المنيو/SITE/armada-menu-site.zip)
into the website as /menu/ — the single-file app is kept as is (frame engine, cart, WhatsApp ordering), split into:

  content/menu.json                 menu data (data/menu_data.json) + the site switches that used to live in CONFIG
                                    + the frame manifest (FRAMES constant) with paths under /menu/frames/
  content/menu-catalog-source.json  data/catalog_source.json, verbatim (reference)
  public/menu/frames/<section>/{desktop,mobile}/frame_NNNN.webp + manifest.json   copied byte for byte (no re-encoding)
  src/styles/legacy-menu.css        the page <style>, scoped under .legacy-menu by scripts/legacy-css.py
  public/legacy/menu.js             the page <script>, verbatim except: CONFIG/DATA/FRAMES/lang are read from the
                                    #armada-menu-cfg JSON the page emits; the in-page language toggle and the legacy
                                    footer bindings are removed (the site header switches /menu/ ↔ /en/menu/).

  python scripts/legacy-menu-port.py
"""
from __future__ import annotations

import ast
import filecmp
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# v19 (brand/cafe → legacy-sites/menu-v19.zip): index.html + data + the printable PDF, no frames —
# the frame sets still come from the first export (legacy-sites/menu.zip).
SRC = ROOT / "legacy-sites/menu-v19-src"
FRAMES_SRC = ROOT / "legacy-sites/menu-src/armada-menu-site/assets/frames"
INDEX = SRC / "index.html"
PDF_NAME = "ARMADA_Cafe_Restaurant_Menu_2026.pdf"
CONTENT = ROOT / "content"
FRAMES_OUT = ROOT / "public/menu/frames"


def section(html: str, tag: str) -> str:
    m = re.search(rf"<{tag}>\n(.*?)\n</{tag}>", html, re.S)
    if not m:
        raise SystemExit(f"<{tag}> block not found in index.html")
    return m.group(1)


def main() -> None:
    html = INDEX.read_text(encoding="utf-8")
    css = section(html, "style")
    js = section(html, "script")

    # ── data ─────────────────────────────────────────────────────────────────────────────────────
    data = json.loads((SRC / "data/menu_data.json").read_text(encoding="utf-8"))
    cfg_src = re.search(r"const CONFIG = \{(.*?)\n\};", js, re.S).group(1)
    hidden = json.loads(re.search(r"hiddenItems:\s*(\[[^\]]*\])", cfg_src).group(1))
    def lit(key):  # JS object literal in CONFIG → Python (unquoted keys allowed); parsed with ast, never executed
        m = re.search(rf"{key}:\s*(\[[^\]]*\]|\{{(?:[^{{}}]|\{{[^{{}}]*\}})*\}}|\d+|\"[^\"]*\")", cfg_src)
        src = re.sub(r"([{,]\s*)([A-Za-z_]\w*)\s*:", lambda g: f'{g.group(1)}"{g.group(2)}":', m.group(1))
        return ast.literal_eval(src)
    frames = json.loads(re.search(r"^const FRAMES = (\{.*\});\s*(?://.*)?$", js, re.M).group(1))
    for folder, fr in frames.items():
        for s in fr["sets"].values():
            s["pattern"] = s["pattern"].replace("assets/frames/", "/menu/frames/")
    data["_note"] = (
        "Café menu as rendered on /menu/ — generated by scripts/legacy-menu-port.py from the legacy menu site "
        "(data/menu_data.json). Prices are café prices in SAR, approved items only are orderable. Re-run the script "
        "after replacing the legacy export; `site` holds the switches that used to live in the page CONFIG."
    )
    data["site"] = {
        "show_pending_items": False,
        "hidden_items": hidden,
        "vip_override": None,
        "scene_length": 1.5,
        "snacks_length": 1.15,
        "morning_order": lit("morningOrder"),
        "day_order": lit("dayOrder"),
        "breakfast_first_until_hour": lit("breakfastFirstUntilHour"),
        "time_zone": lit("timeZone"),
        "service_hours": lit("serviceHours"),
        "pdf": f"/docs/{PDF_NAME}",
        "whatsapp_source": "contact.json → cafe.whatsapp",
        "_note": "show_pending_items false: unapproved items stay hidden (Ahmed, 9 Oct 2026); hidden_items = catalog ids left off the menu",
    }
    # keep the per-scene video entries written by scripts/menu-video.mjs (not part of the legacy export)
    prev = CONTENT / "menu.json"
    if prev.is_file():
        old = json.loads(prev.read_text(encoding="utf-8"))
        for folder, fr in frames.items():
            if folder in old.get("frames", {}) and "video" in old["frames"][folder]:
                fr["video"] = old["frames"][folder]["video"]
        if old.get("frames_note"):
            data["frames_note"] = old["frames_note"]
    data["frames"] = frames
    (CONTENT / "menu.json").write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    shutil.copyfile(SRC / "data/catalog_source.json", CONTENT / "menu-catalog-source.json")
    (ROOT / "public/docs").mkdir(parents=True, exist_ok=True)
    shutil.copyfile(SRC / "assets" / PDF_NAME, ROOT / "public/docs" / PDF_NAME)

    # ── frames: copied as is ────────────────────────────────────────────────────────────────────
    n = 0
    for folder in frames:
        src = FRAMES_SRC / folder
        dst = FRAMES_OUT / folder
        if dst.is_dir() and filecmp.dircmp(src, dst).diff_files == [] and sum(1 for _ in dst.rglob("*.webp")) == sum(1 for _ in src.rglob("*.webp")):
            n += sum(1 for _ in dst.rglob("*.webp"))
            continue
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
        n += sum(1 for _ in dst.rglob("*.webp"))

    # ── css: write the extracted sheet, then scope it (scripts/legacy-css.py → src/styles/legacy-menu.css) ──
    (SRC / "menu-extracted.css").write_text(css, encoding="utf-8", newline="\n")
    subprocess.run([sys.executable, str(ROOT / "scripts/legacy-css.py"), "menu"], check=True)

    # ── js: verbatim with the config/data/frames injected and the language toggle + footer bindings removed ──
    out = js
    out = re.sub(
        r"/\* =+ CONFIGURATION =+ \*/\nconst CONFIG = \{.*?\n\};\n/\* =+ \*/\n",
        '/* CONFIG, DATA, FRAMES and the page language come from the #armada-menu-cfg JSON the page emits (content/menu.json + contact.json) */\n'
        'const CFG = JSON.parse(document.getElementById("armada-menu-cfg").textContent);\n'
        "const CONFIG = CFG.config;\n",
        out, count=1, flags=re.S,
    )
    out = re.sub(r"^const DATA = .*$", "const DATA = CFG.data;", out, count=1, flags=re.M)
    out = re.sub(r"^const FRAMES = .*$", "const FRAMES = CFG.frames;", out, count=1, flags=re.M)
    out = out.replace(
        'let lang = "ar";\nlet cart = {};        // key -> {id,opt,qty}\n'
        'try{ const s=JSON.parse(localStorage.getItem("armada-menu")||"{}"); if(s.lang) lang=s.lang; if(s.cart) cart=s.cart; }catch(e){}',
        'const lang = CFG.lang;   // the site header switches /menu/ ↔ /en/menu/\n'
        'let cart = {};        // key -> {id,opt,qty}\n'
        'try{ const s=JSON.parse(localStorage.getItem("armada-menu")||"{}"); if(s.cart) cart=s.cart; }catch(e){}',
    )
    out = out.replace(
        '  document.documentElement.lang=lang; document.documentElement.dir = lang==="ar"?"rtl":"ltr";\n', "")
    out = out.replace(
        '  document.getElementById("langAr").setAttribute("aria-pressed",lang==="ar"); document.getElementById("langEn").setAttribute("aria-pressed",lang==="en");\n', "")
    out = re.sub(
        r'  document\.getElementById\("footAddr"\)\.textContent=T\("addr"\);\n.*?document\.getElementById\("footCfg"\)\.textContent="";\n',
        "", out, count=1, flags=re.S,
    )
    out = re.sub(r"/\* -+ language -+ \*/\nfunction setLang\(l\)\{.*?\n\}\n.*?langEn.*?\n", "", out, count=1, flags=re.S)
    # ── video scrub mode (9 Oct 2026): one VP9 WebM per scene (scripts/menu-video.mjs → frames[folder].video).
    #    The video element is drawn onto the same canvas (fades + glow unchanged); scrolling seeks currentTime;
    #    frame 0 (webp) is the poster; the frame set stays as the fallback when the video cannot play/decode. ──
    VIDEO_HOOKS = [
        (
            '      url:i=> MODE==="inline"?fr.urls[i]:fr.sets[frameSet()].pattern.replace("%04d",String(i).padStart(4,"0"))});\n',
            '      url:i=> MODE==="inline"?fr.urls[i]:fr.sets[frameSet()].pattern.replace("%04d",String(i).padStart(4,"0")),\n'
            '      vmeta: fr.video||null, video:null, vok:false, vseeking:false, vframe:-1});\n',
        ),
        (
            'function nearestLoaded(sc,i){\n',
            '/* video scrub: create the <video> lazily, seek to the frame the scroll asks for, draw it once the seek lands */\n'
            'const CAN_VIDEO = (()=>{ try{ const v=document.createElement("video"); return !!v.canPlayType && v.canPlayType(\'video/webm; codecs="vp9"\')!==""; }catch(e){ return false; } })();\n'
            'function ensureVideo(sc){\n'
            '  if(sc.video || !sc.vmeta || !CAN_VIDEO) return;\n'
            '  const v=document.createElement("video"); v.muted=true; v.playsInline=true; v.preload="auto"; v.setAttribute("aria-hidden","true");\n'
            '  v.style.cssText="position:absolute;width:1px;height:1px;opacity:0;pointer-events:none";\n'
            '  v.addEventListener("loadeddata",()=>{ sc.vok=true; requestDraw(true); });\n'
            '  v.addEventListener("seeked",()=>{ sc.vseeking=false; sc.vframe=Math.round(v.currentTime*sc.vmeta.fps); requestDraw(true); });\n'
            '  v.addEventListener("error",()=>{ sc.video=null; sc.vok=false; sc.vmeta=null; scheduleWindow(sc,sc.idx,1); });\n'
            '  v.src=sc.vmeta.src; sc.video=v; sc.stage.appendChild(v);\n'
            '}\n'
            'function videoFrame(sc,i){\n'
            '  const v=sc.video; if(!v || !sc.vok) return null;\n'
            '  const fps=sc.vmeta.fps, dur=v.duration||((sc.count-1)/fps); const t=Math.min(dur, Math.max(0, i/fps));\n'
            '  if(!sc.vseeking && Math.abs(v.currentTime-t) > 0.5/fps){ sc.vseeking=true; try{ v.currentTime=t; }catch(e){ sc.vseeking=false; } }\n'
            '  if(sc.vframe<0 && v.readyState<2) return null;\n'
            '  v.i = sc.vframe<0 ? 0 : sc.vframe; return v;\n'
            '}\n'
            'function nearestLoaded(sc,i){\n'
            '  const vf=videoFrame(sc,i); if(vf) return vf;\n',
        ),
        (
            'function scheduleWindow(sc,i,dir){\n',
            'function scheduleWindow(sc,i,dir){\n'
            '  if(sc.vmeta && CAN_VIDEO){ want(sc,0); pump(); ensureVideo(sc); return; }   // poster frame + the video; no frame windows\n',
        ),
    ]
    for old, new in VIDEO_HOOKS:
        if old not in out:
            raise SystemExit(f"menu.js hook anchor not found: {old[:60]!r}")
        out = out.replace(old, new, 1)

    for needle in ("setLang(", "footAddr", "langAr", "const DATA = {", "const FRAMES = {", 'whatsappNumber: "'):
        if needle in out:
            raise SystemExit(f"menu.js still contains {needle!r}")
    header = (
        "/* Generated by scripts/legacy-menu-port.py from the legacy café menu site (index.html <script>) — the frame engine,\n"
        "   cart and WhatsApp ordering are kept as is. Config/data/frames come from #armada-menu-cfg; language from the page. */\n"
    )
    (ROOT / "public/legacy/menu.js").write_text(header + out + "\n", encoding="utf-8", newline="\n")
    approved = sum(1 for i in data["items"] if i.get("approved"))
    print(f"menu.json: {len(data['sections'])} sections, {len(data['items'])} items ({approved} approved); frames: {n} files; menu.js + legacy-menu.css written")


if __name__ == "__main__":
    main()
