#!/usr/bin/env python3
"""
Build content/partners-pages.json from the legacy B2B copy (legacy-sites/b2b.zip → src/content.py) WITHOUT
executing it: the module is parsed with `ast` and every assignment is evaluated as a literal.
The page structure, headings and paragraphs are kept; every fact or figure is then overridden from
content/partners.json, branches.json, rooms.json, halls.json and contact.json (see OVERRIDES below).
Sentences that cannot be backed by content/ are dropped and listed under removed_from_legacy.

  python scripts/legacy-partners-content.py
"""
from __future__ import annotations

import ast
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEGACY = ROOT / "legacy-sites/b2b-src/armada-residence-b2b/src/content.py"
CONTENT = ROOT / "content"


def load(name: str) -> dict:
    return json.loads((CONTENT / name).read_text(encoding="utf-8"))


def legacy_module() -> dict:
    tree = ast.parse(LEGACY.read_text(encoding="utf-8"))
    ns: dict = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            tgt = node.targets[0]
            value = ast.literal_eval(node.value)
            if isinstance(tgt, ast.Name):
                ns[tgt.id] = value
            elif isinstance(tgt, ast.Subscript) and isinstance(tgt.value, ast.Name):
                ns[tgt.value.id][ast.literal_eval(tgt.slice)] = value
    return ns


def pair(v):
    """('en','ar') tuple → {'en':..,'ar':..}; lists/dicts recurse; scalars pass through."""
    if isinstance(v, tuple) and len(v) == 2 and all(isinstance(x, str) for x in v):
        return {"en": v[0], "ar": v[1]}
    if isinstance(v, (list, tuple)):
        return [pair(x) for x in v]
    if isinstance(v, dict):
        return {k: pair(x) for k, x in v.items()}
    return v


def main() -> None:
    L = legacy_module()
    partners, branches, rooms, halls, contact = (load(n) for n in ("partners.json", "branches.json", "rooms.json", "halls.json", "contact.json"))
    f = partners["facts"]
    airport = next(b for b in branches["branches"] if b["slug"] == "airport-road")
    shafa = next(b for b in branches["branches"] if b["slug"] == "shafa-road")
    hall = halls["halls"][0]
    removed: list[str] = []

    def P(key):  # legacy block → bilingual dict structure
        return pair(L[key])

    out = {
        "_note": "Generated by scripts/legacy-partners-content.py from the legacy B2B site copy; facts overridden from content/. Re-run the script instead of editing. Draft copy for Ahmed's review.",
        "ui": P("UI"),
        "nav": P("NAV"),
        "hero": P("HERO_V3"),
        "proposition": P("PROPOSITION"),
        "portfolio": P("PORTFOLIO"),
        "why": P("WHY_V3"),
        "flow": P("FLOW_V3"),
        "umrah": P("UMRAH_V3"),
        "corp": P("CORP_V3"),
        "meet": P("MEET_V3"),
        "built": P("BUILT_V3"),
        "final": P("FINAL_V3"),
        "props": P("PROPS"),
        "segments": P("SEGMENTS"),
        "group_intro": P("GROUP_INTRO"),
        "event_order_note": P("EVENT_ORDER_NOTE"),
        "steps": P("STEPS"),
        "promises": P("PROMISES"),
        "named_contact": P("NAMED_CONTACT"),
        "hall_lead": P("HALL_LEAD"),
        "equipment": [],
        "seating": [],
        "seating_note": P("SEATING_NOTE"),
        "catering": P("CATERING"),
        "agent_gets": P("AGENT_GETS"),
        "in_every_unit": [],
        "group_services": P("GROUP_SERVICES"),
        "unit_note": P("UNIT_NOTE"),
        "calc": P("CALC"),
        "form": P("FORM"),
        "disclaimer": P("DISCLAIMER"),
        "footer": P("FOOTER"),
        "removed_from_legacy": removed,
        "verified": False,
        "pending": ["Ahmed's approval of copy"],
    }

    # ── hero stats / "built" numbers: 12 room types, not 8 ───────────────────────────────────────
    out["hero_stats"] = [
        {"n": f["hotels"], "label": {"en": "Hotels", "ar": "فندقان"}, "sub": {"en": "in Taif", "ar": "في الطائف"}},
        {"n": f["units_total"], "label": {"en": "Combined units", "ar": "إجمالي الوحدات"}, "sub": {"en": "across both properties", "ar": "في الفندقين"}},
        {"n": f["room_types"], "label": {"en": "Room types", "ar": "أنواع الغرف"}, "sub": {"en": "single to two-bedroom", "ar": "من المفردة إلى الجناح"}},
        {"n": f["reply_within_business_days"], "label": {"en": "Working day", "ar": "يوم عمل"}, "sub": {"en": "to reply, in writing", "ar": "للردّ كتابيًا"}},
    ]
    out["hero"]["meta"] = {
        "en": f"{f['hotels']} properties · {f['units_total']} units · B2B hospitality partner",
        "ar": f"فندقان · {f['units_total']} وحدة · شريك ضيافة للشركات ووكلاء السفر",
    }
    removed.append("'8 unit types' hero/built stat and 'Eight ways to place a guest' heading → room types = 12 (rooms.json); the unit table keeps its 8 partner-facing rows")

    # ── properties: counts, drive times, feats, near ────────────────────────────────────────────
    pa, ps = out["props"]["airport"], out["props"]["shafa"]
    pa["count"], ps["count"] = str(f["units_airport"]), str(f["units_shafa"])
    ps["unit"] = {"en": f"Units · {f['beds_shafa']} beds", "ar": f"وحدة · {f['beds_shafa']} سريرًا"}
    pa["lead"] = {
        "en": f"{f['units_airport']} hotel apartments on Airport Road, {f['drive_time_airport_to_airport_road_min']} minutes from Taif airport. This is the property we place organised groups in — the larger inventory, twin rooms, suites with kitchens, the meeting hall, and parking that accommodates a tour coach.",
        "ar": f"{f['units_airport']} شقة فندقية على طريق المطار، على بُعد {f['drive_time_airport_to_airport_road_min']} دقيقة من مطار الطائف. هذا هو الفندق الذي نُسكِّن فيه المجموعات المنظَّمة — السعة الأكبر، والغرف بسريرين، والأجنحة المزوّدة بمطبخ، وقاعة الاجتماعات، والمواقف التي تتّسع لحافلة سياحية.",
    }
    ps["lead"] = {
        "en": f"{f['units_shafa']} units and {f['beds_shafa']} beds on Al-Shafa Road, {f['drive_time_ruddaf_to_shafa_min']} minutes from Al Ruddaf Park — quieter and smaller than Airport Road, built around family groups booked through agencies and leisure stays.",
        "ar": f"{f['units_shafa']} وحدة و{f['beds_shafa']} سريرًا على طريق الشفا، على بُعد {f['drive_time_ruddaf_to_shafa_min']} دقائق من حديقة الردف — أهدأ وأصغر من طريق المطار، وقائم على المجموعات العائلية عبر الوكالات والإقامات الترفيهية.",
    }
    removed.append("Airport Road lead: 'on the Al Hada corridor towards Makkah Al-Mukarramah' (corridor claim not in content/)")
    removed.append("Shafa Road lead: 'in Al-Sadad, an established residential quarter … minutes from the parks' (district-character claim; replaced by the confirmed 4 min to Al Ruddaf)")
    pa["stats"] = [
        {"n": str(f["units_airport"]), "label": {"en": "Apartments", "ar": "شقة"}},
        {"n": str(len([r for r in rooms["rooms"] if r["branch"] == "airport-road" and r["show_on_site"]])), "label": {"en": "Unit types", "ar": "أنواع وحدات"}},
        {"n": str(f["hall"]["capacity"]), "label": {"en": "Hall capacity", "ar": "سعة القاعة"}},
        {"n": str(f["drive_time_airport_to_airport_road_min"]), "label": {"en": "Min to airport", "ar": "دقيقة للمطار"}},
    ]
    ps["stats"] = [
        {"n": str(f["units_shafa"]), "label": {"en": "Units", "ar": "وحدة"}},
        {"n": str(f["beds_shafa"]), "label": {"en": "Beds", "ar": "سريرًا"}},
        {"n": str(f["drive_time_ruddaf_to_shafa_min"]), "label": {"en": "Min · Al Ruddaf", "ar": "دقائق · الردف"}},
        {"n": str(len([r for r in rooms["rooms"] if r["branch"] == "shafa-road" and r["show_on_site"]])), "label": {"en": "Unit types", "ar": "أنواع وحدات"}},
    ]
    removed.append("Shafa stat '8 min · Taif Zoo' and Airport/Shafa 'Getting there' rows except the two confirmed drive times (Al Abbas Mosque, City Centre, Jouri Mall, Terra Mall, Al Hada area, Ruddaf 8 min, Zoo 8 min)")
    pa["near"] = [{"en": "Taif International Airport", "ar": "مطار الطائف الدولي", "den": f"{f['drive_time_airport_to_airport_road_min']} min", "dar": f"{f['drive_time_airport_to_airport_road_min']} دقيقة"}]
    ps["near"] = [{"en": "Al Ruddaf Park", "ar": "حديقة الردف", "den": f"{f['drive_time_ruddaf_to_shafa_min']} min", "dar": f"{f['drive_time_ruddaf_to_shafa_min']} دقائق"}]
    svc_ar, svc_en = airport["services_ar"], airport["services_en"]
    pa["feats"] = [
        [{"en": "Meeting hall", "ar": "قاعة اجتماعات"}, {"en": f"Up to {f['hall']['capacity']} people — equipment and seating confirmed", "ar": f"حتى {f['hall']['capacity']} شخصًا — تجهيزات وأنماط جلوس مؤكدة"}],
        [{"en": "Restaurant & coffee shop", "ar": "مطعم وكوفي شوب"}, {"en": "Group buffets served in-house", "ar": "بوفيهات المجموعات من مطبخنا"}],
        [{"en": "Coach parking", "ar": "مواقف الحافلات"}, {"en": "On-site, tour-coach capacity", "ar": "داخل الموقع، تتّسع لحافلة سياحية"}],
        [{"en": "Free Wi-Fi", "ar": "واي فاي مجاني"}, {"en": "All units and public areas", "ar": "كل الوحدات والمناطق العامة"}],
        [{"en": "24-hour reception", "ar": "استقبال على مدار الساعة"}, {"en": "Organised group arrivals", "ar": "وصول جماعي منظَّم"}],
        [{"en": " · ".join(svc_en), "ar": " · ".join(svc_ar)}, {"en": "At both properties", "ar": "في الفرعين"}],
    ]
    ps["feats"] = [
        [{"en": "Restaurant & café", "ar": "مطعم ومقهى"}, {"en": "Daily breakfast buffet and group meals", "ar": "بوفيه إفطار يومي ووجبات المجموعات"}],
        [{"en": "Coach parking", "ar": "مواقف الحافلات"}, {"en": "On-site, tour-coach capacity", "ar": "داخل الموقع، تتّسع لحافلة سياحية"}],
        [{"en": "Free Wi-Fi", "ar": "واي فاي مجاني"}, {"en": "All units and public areas", "ar": "كل الوحدات والمناطق العامة"}],
        [{"en": "24-hour reception", "ar": "استقبال على مدار الساعة"}, {"en": "Organised group arrivals", "ar": "وصول جماعي منظَّم"}],
        [{"en": " · ".join(svc_en), "ar": " · ".join(svc_ar)}, {"en": "At both properties", "ar": "في الفرعين"}],
    ]
    removed.append("Shafa feats 'Armada Residence Café — coffee · teas · juices · pastries', 'Breakfast restaurant seating for the whole party', 'Accessible units — on request'; Airport 'Free high-speed Wi-Fi' → Wi-Fi (speed not confirmed)")
    pa["gallery"] = [["function-hall", {"en": "The function hall", "ar": "قاعة المناسبات"}], ["suite-living", {"en": "Suite living room", "ar": "صالة الجناح"}]]
    ps["gallery"] = [["shafa-exterior", {"en": "Al-Shafa Road", "ar": "طريق الشفا"}]]
    removed.append("Gallery photos not in the approved set (heritage-majlis, lounge-airport, king-shafa, twin-shafa, jacuzzi-shafa, cafe-shafa, group-buffet, boardroom, suite-two-bed, twin-airport, lobby-airport, king-airport, king-junior, terrace)")

    # ── portfolio facts ──────────────────────────────────────────────────────────────────────────
    out["portfolio"][0][3] = [
        {"en": f"{f['units_airport']} hotel apartments", "ar": f"{f['units_airport']} شقة فندقية"},
        {"en": "Suitable for groups and long stay", "ar": "مناسب للمجموعات والإقامة الطويلة"},
        {"en": f"{f['drive_time_airport_to_airport_road_min']} minutes from Taif Airport", "ar": f"{f['drive_time_airport_to_airport_road_min']} دقيقة من مطار الطائف"},
        {"en": "Meeting hall and coach parking", "ar": "قاعة اجتماعات ومواقف للحافلات"},
    ]
    out["portfolio"][1][3] = [
        {"en": f"{f['units_shafa']} units · {f['beds_shafa']} beds", "ar": f"{f['units_shafa']} وحدة · {f['beds_shafa']} سريرًا"},
        {"en": f"{f['drive_time_ruddaf_to_shafa_min']} minutes from Al Ruddaf Park", "ar": f"{f['drive_time_ruddaf_to_shafa_min']} دقائق من حديقة الردف"},
        {"en": "Family groups via agencies and leisure", "ar": "المجموعات العائلية عبر الوكالات والسياحة"},
        {"en": "Coach parking", "ar": "مواقف للحافلات"},
    ]
    removed.append("Portfolio: 'Al Hada road towards Makkah', '8 minutes from Al Ruddaf Park' (confirmed 4), 'Armada Residence Café'")
    out["why"]["items"][3] = [
        {"en": "Strategic Taif location", "ar": "موقع استراتيجي في الطائف"},
        {"en": f"Airport Road is {f['drive_time_airport_to_airport_road_min']} minutes from Taif International Airport; Al-Shafa Road is {f['drive_time_ruddaf_to_shafa_min']} minutes from Al Ruddaf Park.", "ar": f"طريق المطار على بُعد {f['drive_time_airport_to_airport_road_min']} دقيقة من مطار الطائف الدولي، وطريق الشفا على بُعد {f['drive_time_ruddaf_to_shafa_min']} دقائق من حديقة الردف."},
        "",
    ]
    out["footer"]["blurb"] = {"en": f"Two hotels in Taif — {f['units_total']} units, {f['room_types']} room types and one commercial contact for the travel trade.", "ar": f"فندقان في الطائف — {f['units_total']} وحدة و{f['room_types']} نوع غرفة ومسؤول تجاري واحد لقطاع السفر."}

    # ── process promises not backed by content/ → softened ──────────────────────────────────────
    out["steps"][1][2] = {"en": "Availability comes back within one working day, with a written offer.", "ar": "تعود الإتاحة خلال يوم عمل واحد، ومعها عرض مكتوب."}
    out["steps"][2][2] = {"en": "Unit mix and meal arrangement are confirmed in writing and the allocation is held.", "ar": "يُعتمد توزيع الوحدات وترتيب الوجبات كتابةً، ويُحجز التخصيص."}
    out["steps"][3][2] = {"en": "Reviewed with the commercial office before arrival — names, pairings and special requests.", "ar": "تُراجَع مع المكتب التجاري قبل الوصول — الأسماء والتوزيع والطلبات الخاصة."}
    out["steps"][4] = ["05", {"en": "The arrival plan", "ar": "خطة الوصول"}, {"en": "Arrival, rooming, meals and hall use are agreed in writing before the group lands.", "ar": "يُتَّفق كتابةً على الوصول والتسكين والوجبات واستخدام القاعة قبل وصول المجموعة."}]
    out["steps"][5][2] = {"en": "Group check-in handled as one movement, and the account settled on departure.", "ar": "تسجيل دخول جماعي يُنجَز كحركة واحدة، وتسوية الحساب عند المغادرة."}
    out["promises"] = [["1", {"en": "Named contact", "ar": "مسؤول باسمه"}], ["1", {"en": "Working day to reply", "ar": "يوم عمل للردّ"}], ["1", {"en": "Written offer", "ar": "عرض مكتوب"}]]
    out["event_order_note"] = {"en": "<b>One written plan, agreed before arrival:</b> every confirmed group has its arrival, rooming, meals and hall use agreed in writing with the commercial office before the group lands.", "ar": "<b>خطة واحدة مكتوبة تُتَّفق قبل الوصول:</b> كل مجموعة مؤكَّدة يُتَّفق كتابةً مع المكتب التجاري على وصولها وتسكينها ووجباتها واستخدام القاعة قبل أن تصل."}
    out["flow"]["steps"][2][1] = {"en": "A written offer with unit mix and meal arrangement.", "ar": "عرض مكتوب مع توزيع الوحدات وترتيب الوجبات."}
    out["flow"]["steps"][3][1] = {"en": "The allocation is held and the arrival plan is agreed in writing.", "ar": "يُحجز التخصيص ويُتَّفق على خطة الوصول كتابةً."}
    out["why"]["items"][1][1] = {"en": "Umrah groups, sports teams, corporate programmes and institutional delegations — rooming lists reviewed with the commercial office before arrival.", "ar": "مجموعات العمرة والفرق الرياضية وبرامج الشركات والوفود المؤسسية — قوائم التسكين تُراجَع مع المكتب التجاري قبل الوصول."}
    out["why"]["items"][4] = [{"en": "Written before it happens", "ar": "مكتوب قبل التنفيذ"}, {"en": "Every confirmed group has its arrival plan agreed in writing before it lands.", "ar": "كل مجموعة مؤكَّدة تُتَّفق خطة وصولها كتابةً قبل أن تصل."}, ""]
    out["agent_gets"][2][2] = {"en": "Reviewed with the commercial office before arrival.", "ar": "تُراجَع مع المكتب التجاري قبل الوصول."}
    out["agent_gets"][4] = ["05", {"en": "Group meals from our kitchen", "ar": "وجبات المجموعات من مطبخنا"}, pair((partners["facts"]["group_meals"]["note_en"], partners["facts"]["group_meals"]["note_ar"]))]
    out["agent_gets"][5][2] = {"en": "Airport Road suites with kitchens.", "ar": "أجنحة طريق المطار المزوّدة بمطبخ."}
    out["corp"]["body"] = {"en": "Company accommodation programmes, business stays with a meeting hall, and long stays in hotel apartments with kitchens on Airport Road — with one commercial contact for the account.", "ar": "برامج إسكان الشركات، وإقامات عمل مع قاعة اجتماعات، وإقامات طويلة في شقق فندقية بمطبخ على طريق المطار — مع مسؤول تجاري واحد للحساب."}
    out["umrah"]["body"] = {"en": "Group stays in Taif, multi-bed rooming for the whole party and meals served from our own kitchen — arranged on one file, under one agreement.", "ar": "إقامات المجموعات في الطائف، وتسكين متعدد الأسرّة للوفد كاملًا، ووجبات من مطبخنا — في ملف واحد وتحت اتفاقية واحدة."}
    out["umrah"]["list"][3] = pair((partners["facts"]["group_meals"]["note_en"], partners["facts"]["group_meals"]["note_ar"]))
    out["segments"][0][3][0] = {"en": "Group stays in Taif for Umrah parties", "ar": "إقامات في الطائف لمجموعات العمرة"}
    out["group_intro"] = {"en": "A group is not a stack of individual bookings. It arrives together, eats together and leaves together — and it is run from one written plan agreed with the commercial office before the group lands.", "ar": "المجموعة ليست كومة حجوزات فردية. تصل معًا وتأكل معًا وتغادر معًا — وتُدار بخطة واحدة مكتوبة يُتَّفق عليها مع المكتب التجاري قبل وصول المجموعة."}
    out["named_contact"] = {"en": "<b>One named contact.</b> The same person answers the first enquiry and follows the group through to the invoice.", "ar": "<b>مسؤول واحد باسمه.</b> الشخص نفسه يردّ على أول استفسار ويتابع المجموعة حتى الفاتورة."}
    removed.append("Process promises reworded (no content backing): 'contracted rate sheet', 'event order circulated to reception/housekeeping/F&B/accounts', 'rooming lists amended up to the agreed cut-off', 'consolidated billing / one consolidated account', 'upgrades for group leaders', 'no hand-offs, no queue'")
    removed.append("Umrah segment 'Transit stays on the route towards Makkah' → 'Group stays in Taif for Umrah parties'")

    # ── hall: equipment + seating from halls.json (confirmed 9 Oct) ─────────────────────────────
    feats_en, feats_ar = hall["features_en"], hall["features_ar"]
    out["equipment"] = [{"en": e, "ar": a} for e, a in zip(feats_en[:4], feats_ar[:4])]
    out["seating"] = [
        [{"en": "Theatre", "ar": "مسرحي"}, {"en": "On request", "ar": "عند الطلب"}],
        [{"en": "Classroom", "ar": "صف دراسي"}, {"en": "On request", "ar": "عند الطلب"}],
        [{"en": "U-shape", "ar": "على شكل U"}, {"en": "On request", "ar": "عند الطلب"}],
        [{"en": "Boardroom", "ar": "طاولة اجتماعات"}, {"en": "On request", "ar": "عند الطلب"}],
        [{"en": "Rounds", "ar": "طاولات مستديرة"}, {"en": "On request", "ar": "عند الطلب"}],
    ]
    out["seating_note"] = {"en": f"Five seating layouts — capacity for each layout is confirmed on enquiry. The hall is listed at a capacity of {hall['capacity']}.", "ar": f"خمسة أنماط جلوس — تُؤكَّد السعة لكل نمط عند الطلب. والقاعة مُدرَجة بسعة {hall['capacity']}."}
    chef_en, chef_ar = partners["facts"]["group_meals"]["note_en"], partners["facts"]["group_meals"]["note_ar"]
    out["catering"][2] = [{"en": "An executive chef", "ar": "شيف تنفيذي"}, {"en": chef_en, "ar": chef_ar}]
    out["catering"][0][1] = {"en": "Between sessions, inside the hall — " + feats_en[5].lower(), "ar": "بين الجلسات وداخل القاعة — " + feats_ar[5]}
    out["catering"][3] = [{"en": "One agreement", "ar": "اتفاقية واحدة"}, {"en": "Hall, catering and rooms arranged together", "ar": "القاعة والضيافة والتسكين تُرتَّب معًا"}]
    out["hall_lead"] = {"en": f"One equipped hall at Airport Road for up to {hall['capacity']} people, arranged alongside the stay and served from our own kitchen — so the coffee break, the lunch and the rooms all sit on the same written plan.", "ar": f"قاعة واحدة مجهَّزة في طريق المطار تتسع حتى {hall['capacity']} شخصًا، تُهيَّأ إلى جانب الإقامة وتُخدَم من مطبخنا — فيجتمع الكوفي بريك والغداء والتسكين على خطة واحدة مكتوبة."}
    removed.append("Coffee-break menu detail (Arabic and specialty coffee, tea, pastries, fruit, water) and 'Round banquet — default set-up' (halls.json lists the five layouts without a default)")

    # ── in every unit: from rooms.json / branches.json ───────────────────────────────────────────
    out["in_every_unit"] = [
        {"en": "Wi-Fi · TV · in-room safe · air conditioning", "ar": "واي فاي · تلفاز · خزنة داخل الغرفة · تكييف"},
        {"en": "Electric kettle · iron", "ar": "غلاية مياه · مكواة"},
        {"en": "Refrigerator in every Airport Road unit", "ar": "ثلاجة في كل وحدات طريق المطار"},
        {"en": "Kitchen in the Airport Road one- and two-bedroom suites", "ar": "مطبخ في أجنحة طريق المطار بغرفة أو غرفتين"},
        {"en": " · ".join(svc_en) + " — both properties", "ar": " · ".join(svc_ar) + " — في الفرعين"},
    ]
    removed.append("In-unit list: Smart TV 65\"/42\", ironing board, premium amenities, extra mattresses/blankets/pillows, walk-in shower, cotton towels, 'kitchenette in the two-bedroom suites' (kitchens: both Airport Road suites), accessible units with handrails")
    out["group_services"] = [
        [{"en": "Complimentary Wi-Fi", "ar": "واي فاي مجاني"}, {"en": "All units and public areas, both hotels", "ar": "كل الوحدات والمناطق العامة في الفندقين"}],
        [{"en": "24-hour reception & security", "ar": "استقبال وأمن على مدار الساعة"}, {"en": "Organised group check-in and check-out", "ar": "تسجيل دخول ومغادرة جماعي منظَّم"}],
        [{"en": "Daily housekeeping", "ar": "تدبير غرف يومي"}, {"en": "Room service around the clock", "ar": "خدمة غرف على مدار الساعة"}],
    ]

    # ── unit table from partners.json room_table + rooms.json beds ──────────────────────────────
    def bed(ref: str, lang: str) -> str:
        br, sl = ref.split("|")[0].strip().split("/")
        r = next(x for x in rooms["rooms"] if x["branch"] == br and x["slug"] == sl)
        return r[f"bed_{lang}"]

    rows = []
    for row in partners["room_table"]["rows"]:
        hotel = {"airport-road": {"en": "Airport", "ar": "المطار"}, "shafa-road": {"en": "Al Shafa", "ar": "الشفا"}, "both": {"en": "Both", "ar": "الفندقان"}}[row["hotel"]]
        occ = str(row["occupancy"])
        rows.append({
            "type": {"en": row["label_en"], "ar": row["label_ar"]},
            "occupancy": {"en": f"{occ} guest" if occ == "1" else f"{occ} guests", "ar": {"1": "ضيف واحد", "2": "ضيفان", "4": "حتى 4 ضيوف"}.get(occ, f"{occ} ضيوف")},
            "beds": {"en": row.get("beds_en") or bed(row["room"], "en"), "ar": row.get("beds_ar") or bed(row["room"], "ar")},
            "hotel": hotel,
            "best": {"en": row["recommended_en"], "ar": row["recommended_ar"]},
            "hotel_key": row["hotel"],
            "room": row["room"],
        })
    out["units"] = rows
    out["unit_head"] = P("UNIT_HEAD")
    out["unit_note"] = {"en": f"Unit counts per type are confirmed with each enquiry — combined inventory is <b>{f['units_total']} units</b> across the two properties.", "ar": f"يُؤكَّد عدد الوحدات لكل نوع مع كل طلب — وإجمالي المعروض <b>{f['units_total']} وحدة</b> في الفندقين."}
    removed.append("Legacy unit rows replaced by partners.json room_table: 'Twin Room — Both' (twin is Airport Road only), 'Family Suite', 'Jacuzzi Room', 'Two-Bedroom / Executive Suite', 'Jacuzzi Suite — occupancy confirmed on enquiry'")

    # calculator units: from rooms.json capacities
    out["calc_units"] = [
        {"key": "single", "en": "Single room (king, one guest)", "ar": "غرفة مفردة (كينج لضيف واحد)", "cap": 1, "props": ["airport"]},
        {"key": "twin", "en": "Twin room", "ar": "غرفة بسريرين", "cap": 2, "props": ["airport"]},
        {"key": "king", "en": "King room", "ar": "غرفة كينج", "cap": 2, "props": ["airport", "shafa"]},
        {"key": "suite1", "en": "One-bedroom suite", "ar": "جناح غرفة وصالة", "cap": 3, "props": ["airport", "shafa"]},
        {"key": "suite2", "en": "Two-bedroom suite", "ar": "جناح غرفتي نوم وصالة", "cap": 4, "props": ["airport", "shafa"]},
        {"key": "suite2j", "en": "Two-bedroom jacuzzi suite", "ar": "جناح غرفتي نوم وجاكوزي", "cap": 4, "props": ["shafa"]},
    ]
    removed.append("Rooming calculator unit list ('Family Suite', 'Executive Suite', twin at Shafa) → rooms.json types and capacities")

    # ── rate window / fact sheet / addresses ────────────────────────────────────────────────────
    removed.append("'Special corporate & travel-trade rates — held to the end of the year / Valid to 31 Dec 2026' block")
    removed.append("'Fact Sheet 2026 (PDF)' download links (the PDF carries the removed figures)")
    removed.append("'حي القمم الأعلى' → address from branches.json (حي القيم الأعلى)")
    out["address"] = {"airport": {"en": airport["address_en"], "ar": airport["address_ar"]}, "shafa": {"en": shafa["address_en"], "ar": shafa["address_ar"]}}
    c = partners["contact"]
    out["contact"] = {
        "sales_manager": c["sales_manager"], "show_name": c["show_name"], "phone": c["phone"],
        "phone_display": contact["sales"]["phone_display"], "whatsapp": c["whatsapp"], "email": c["email"],
        "reservations": c["reservations_email"], "linktree": c["linktree"],
        "sales_manager_title": {"en": "Sales Manager", "ar": "مدير المبيعات"},
    }
    # enquiry form: request types limited to partners.json enquiry_types; no fact-sheet download
    types = partners["enquiry_types"]
    out["form"]["reqtypes"] = [r for r in out["form"]["reqtypes"] if r[0] in types]
    out["form"]["properties"] = [["airport-road", {"en": "Airport Road", "ar": "طريق المطار"}], ["shafa-road", {"en": "Al Shafa Road", "ar": "طريق الشفا"}], ["both", {"en": "Both properties", "ar": "الفندقان معًا"}]]
    removed.append("Enquiry request types not in partners.json → enquiry_types (group-quote, long-stay, other) and 'Advise me' property option")
    out["form"]["unittype_placeholder"] = {"en": "e.g. 10 twin, 4 two-bedroom suites", "ar": "مثال: 10 غرف بسريرين، 4 أجنحة غرفتين"}
    out["form"]["send"] = {"en": "Send the enquiry", "ar": "أرسل الطلب"}
    out["form"]["sent_title"] = {"en": "Your enquiry has reached the commercial office", "ar": "وصل طلبكم إلى المكتب التجاري"}
    out["form"]["sent_body"] = {"en": "The sales team will come back to you in writing within one working day.", "ar": "سيعود إليكم فريق المبيعات كتابةً خلال يوم عمل واحد."}
    out["form"]["sent_ref"] = {"en": "Request number", "ar": "رقم الطلب"}
    out["form"]["what_to_send"] = {"en": "<b>What to send.</b> The programme, the dates and the party size are enough for a first answer. A rooming list can follow.", "ar": "<b>ما الذي ترسله.</b> البرنامج والتواريخ وعدد الأفراد تكفي للحصول على أول إجابة. وقائمة التسكين يمكن أن تتبع."}
    out["form"]["direct_lines"] = {"en": "Direct lines", "ar": "خطوط مباشرة"}
    out["form"]["our_addresses"] = {"en": "Our addresses", "ar": "عناويننا"}

    (CONTENT / "partners-pages.json").write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"partners-pages.json written: {len(rows)} unit rows, {len(removed)} removal notes")


if __name__ == "__main__":
    main()
