#!/usr/bin/env python3
"""
Port the legacy café menu site (legacy-sites/menu-src/armada-menu-site/, from brand/cafe/المنيو/SITE/armada-menu-site.zip)
into the website as /menu/ — the single-file app is kept as is (frame engine, cart, WhatsApp ordering), split into:

  content/menu.json                 menu data (data/menu_data.json) + the site switches that used to live in CONFIG
                                    + the frame manifest (FRAMES constant) with paths under /menu/frames/
  content/menu-catalog-source.json  data/catalog_source.json, verbatim (reference)
  public/menu/frames/<section>/{desktop,mobile}/frame_NNNN.webp + manifest.json   copied byte for byte (no re-encoding)
  src/styles/legacy-menu.css        the page <style>, scoped under .legacy-menu by scripts/legacy-css.py
  public/legacy/menu.js             the page <script>, verbatim except: CONFIG/DATA/FRAMES/lang are read from the
                                    #armada-menu-cfg JSON the page emits; the in-page language toggle and the legacy
                                    footer bindings are removed (the site header switches /menu/ ↔ /en/menu/).

  python scripts/legacy-menu-port.py
"""
from __future__ import annotations

import filecmp
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "legacy-sites/menu-src/armada-menu-site"
INDEX = SRC / "index.html"
CONTENT = ROOT / "content"
FRAMES_OUT = ROOT / "public/menu/frames"


def section(html: str, tag: str) -> str:
    m = re.search(rf"<{tag}>\n(.*?)\n</{tag}>", html, re.S)
    if not m:
        raise SystemExit(f"<{tag}> block not found in index.html")
    return m.group(1)


def main() -> None:
    html = INDEX.read_text(encoding="utf-8")
    css = section(html, "style")
    js = section(html, "script")

    # ── data ─────────────────────────────────────────────────────────────────────────────────────
    data = json.loads((SRC / "data/menu_data.json").read_text(encoding="utf-8"))
    cfg_src = re.search(r"const CONFIG = \{(.*?)\n\};", js, re.S).group(1)
    hidden = json.loads(re.search(r"hiddenItems:\s*(\[[^\]]*\])", cfg_src).group(1))
    frames = json.loads(re.search(r"^const FRAMES = (\{.*\});\s*(?://.*)?$", js, re.M).group(1))
    for folder, fr in frames.items():
        for s in fr["sets"].values():
            s["pattern"] = s["pattern"].replace("assets/frames/", "/menu/frames/")
    data["_note"] = (
        "Café menu as rendered on /menu/ — generated by scripts/legacy-menu-port.py from the legacy menu site "
        "(data/menu_data.json). Prices are café prices in SAR, approved items only are orderable. Re-run the script "
        "after replacing the legacy export; `site` holds the switches that used to live in the page CONFIG."
    )
    data["site"] = {
        "show_pending_items": False,
        "hidden_items": hidden,
        "vip_override": None,
        "scene_length": 1.5,
        "snacks_length": 1.15,
        "whatsapp_source": "contact.json → cafe.whatsapp",
        "_note": "show_pending_items false: unapproved items stay hidden (Ahmed, 9 Oct 2026); hidden_items = catalog ids left off the menu",
    }
    data["frames"] = frames
    (CONTENT / "menu.json").write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")
    shutil.copyfile(SRC / "data/catalog_source.json", CONTENT / "menu-catalog-source.json")

    # ── frames: copied as is ────────────────────────────────────────────────────────────────────
    n = 0
    for folder in frames:
        src = SRC / "assets/frames" / folder
        dst = FRAMES_OUT / folder
        if dst.is_dir() and filecmp.dircmp(src, dst).diff_files == [] and sum(1 for _ in dst.rglob("*.webp")) == sum(1 for _ in src.rglob("*.webp")):
            n += sum(1 for _ in dst.rglob("*.webp"))
            continue
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
        n += sum(1 for _ in dst.rglob("*.webp"))

    # ── css: write the extracted sheet, then scope it (scripts/legacy-css.py → src/styles/legacy-menu.css) ──
    (SRC / "menu-extracted.css").write_text(css, encoding="utf-8", newline="\n")
    subprocess.run([sys.executable, str(ROOT / "scripts/legacy-css.py"), "menu"], check=True)

    # ── js: verbatim with the config/data/frames injected and the language toggle + footer bindings removed ──
    out = js
    out = re.sub(
        r"/\* =+ CONFIGURATION =+ \*/\nconst CONFIG = \{.*?\n\};\n/\* =+ \*/\n",
        '/* CONFIG, DATA, FRAMES and the page language come from the #armada-menu-cfg JSON the page emits (content/menu.json + contact.json) */\n'
        'const CFG = JSON.parse(document.getElementById("armada-menu-cfg").textContent);\n'
        "const CONFIG = CFG.config;\n",
        out, count=1, flags=re.S,
    )
    out = re.sub(r"^const DATA = .*$", "const DATA = CFG.data;", out, count=1, flags=re.M)
    out = re.sub(r"^const FRAMES = .*$", "const FRAMES = CFG.frames;", out, count=1, flags=re.M)
    out = out.replace(
        'let lang = "ar";\nlet cart = {};        // key -> {id,opt,qty}\n'
        'try{ const s=JSON.parse(localStorage.getItem("armada-menu")||"{}"); if(s.lang) lang=s.lang; if(s.cart) cart=s.cart; }catch(e){}',
        'const lang = CFG.lang;   // the site header switches /menu/ ↔ /en/menu/\n'
        'let cart = {};        // key -> {id,opt,qty}\n'
        'try{ const s=JSON.parse(localStorage.getItem("armada-menu")||"{}"); if(s.cart) cart=s.cart; }catch(e){}',
    )
    out = out.replace(
        '  document.documentElement.lang=lang; document.documentElement.dir = lang==="ar"?"rtl":"ltr";\n', "")
    out = out.replace(
        '  document.getElementById("langAr").setAttribute("aria-pressed",lang==="ar"); document.getElementById("langEn").setAttribute("aria-pressed",lang==="en");\n', "")
    out = re.sub(
        r'  document\.getElementById\("footAddr"\)\.textContent=T\("addr"\);\n.*?document\.getElementById\("footCfg"\)\.textContent="";\n',
        "", out, count=1, flags=re.S,
    )
    out = re.sub(r"/\* -+ language -+ \*/\nfunction setLang\(l\)\{.*?\n\}\n.*?langEn.*?\n", "", out, count=1, flags=re.S)
    for needle in ("setLang(", "footAddr", "langAr", "const DATA = {", "const FRAMES = {", 'whatsappNumber: "'):
        if needle in out:
            raise SystemExit(f"menu.js still contains {needle!r}")
    header = (
        "/* Generated by scripts/legacy-menu-port.py from the legacy café menu site (index.html <script>) — the frame engine,\n"
        "   cart and WhatsApp ordering are kept as is. Config/data/frames come from #armada-menu-cfg; language from the page. */\n"
    )
    (ROOT / "public/legacy/menu.js").write_text(header + out + "\n", encoding="utf-8", newline="\n")
    approved = sum(1 for i in data["items"] if i.get("approved"))
    print(f"menu.json: {len(data['sections'])} sections, {len(data['items'])} items ({approved} approved); frames: {n} files; menu.js + legacy-menu.css written")


if __name__ == "__main__":
    main()
