// Encode every café-menu scene (public/menu/frames/<section>/desktop/frame_NNNN.webp, 15 fps) into a muted VP9 WebM
// (public/menu/video/<section>.webm) and record it in content/menu.json → frames[<section>].video so /menu/ can
// scrub the video with currentTime instead of fetching 151 frames (the frames stay as the fallback and the poster).
//   node scripts/menu-video.mjs            (needs ffmpeg with libvpx-vp9 on PATH or FFMPEG=path)
//   MENU_VIDEO_CRF=38 node scripts/menu-video.mjs
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const FFMPEG = process.env.FFMPEG || 'ffmpeg';
const CRF = process.env.MENU_VIDEO_CRF || '38';
const menuPath = resolve(ROOT, 'content/menu.json');
const menu = JSON.parse(readFileSync(menuPath, 'utf8'));
const outDir = resolve(ROOT, 'public/menu/video');
mkdirSync(outDir, { recursive: true });

let total = 0;
for (const [folder, fr] of Object.entries(menu.frames)) {
  const pattern = resolve(ROOT, 'public', fr.sets.desktop.pattern.replace(/^\//, ''));
  const first = pattern.replace('%04d', '0000');
  if (!existsSync(first)) throw new Error(`frames missing for ${folder}`);
  const out = resolve(outDir, `${folder}.webm`);
  execFileSync(FFMPEG, ['-y', '-hide_banner', '-loglevel', 'error', '-framerate', '15', '-i', pattern, '-c:v', 'libvpx-vp9', '-b:v', '0', '-crf', CRF, '-g', '15', '-row-mt', '1', '-deadline', 'good', '-cpu-used', '2', '-pix_fmt', 'yuv420p', '-an', out], { stdio: 'inherit' });
  const bytes = statSync(out).size;
  total += bytes;
  fr.video = { src: `/menu/video/${folder}.webm`, type: 'video/webm; codecs=vp9', width: fr.sets.desktop.width, height: Math.round((fr.sets.desktop.width * 898) / 720), fps: 15, count: fr.count, bytes, crf: Number(CRF) };
  console.log(`${folder}.webm ${(bytes / 1024 / 1024).toFixed(2)} MB`);
}
menu.frames_note = 'video: one VP9 WebM per scene generated by scripts/menu-video.mjs from the desktop frames (15 fps, no audio); the page scrubs it by currentTime and falls back to the frame set when the browser cannot play it. poster = frame_0000.webp.';
writeFileSync(menuPath, JSON.stringify(menu, null, 2) + '\n');
console.log(`total ${(total / 1024 / 1024).toFixed(2)} MB for ${Object.keys(menu.frames).length} scenes → content/menu.json updated`);
